name: Test 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno test --allow-none --coverage=cov/
      - run: deno coverage --lcov cov/ > cov.lcov
      - name: check lint
        continue-on-error: true
        run: deno lint
      - name: check fmt
        continue-on-error: true
        run: deno fmt --check
